name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            os_version: 1
          - os: windows-latest
            os_version: 2
          - os: ubuntu-latest
            os_version: 3

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: make build directory
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: setup tests
      shell: bash
      working-directory: ${{github.workspace}}/tests/gitrepo
      run: cp -R .notgit .git

    - name: configure cmake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DOS_VERSION=${{ matrix.os_version }} -DBUILD_TESTS=ON

    - name: build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .    

    - name: run tests
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ctest --output-on-failure
    
    - name: cleanup tests
      shell: bash
      working-directory: ${{github.workspace}}/tests/gitrepo
      run: rm -rf -R .git

